"""empty message

Revision ID: 3df4321b1e29
Revises: 9a50923bc3f4
Create Date: 2019-09-15 13:31:22.442202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df4321b1e29'
down_revision = '9a50923bc3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'title')
    # ### end Alembic commands ###
