"""empty message

Revision ID: 781a0cb0859d
Revises: a1c268412cb5
Create Date: 2019-09-15 02:59:35.185217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781a0cb0859d'
down_revision = 'a1c268412cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('discussion', sa.Column('creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discussion', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discussion', type_='foreignkey')
    op.drop_column('discussion', 'creator')
    op.drop_column('discussion', 'creation_date')
    # ### end Alembic commands ###
