"""empty message

Revision ID: 817c46187e23
Revises: ef4b77337603
Create Date: 2019-09-14 23:56:25.915906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817c46187e23'
down_revision = 'ef4b77337603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('name', sa.Text(), nullable=False))
    op.alter_column('discussion', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('option', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'text')
    op.alter_column('discussion', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('discussion', 'name')
    # ### end Alembic commands ###
