"""empty message

Revision ID: 98c4fd35316e
Revises: ab94b516a6a5
Create Date: 2019-09-15 11:31:16.045506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c4fd35316e'
down_revision = 'ab94b516a6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('closed', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion', 'closed')
    # ### end Alembic commands ###
