"""empty message

Revision ID: a1c268412cb5
Revises: 817c46187e23
Create Date: 2019-09-15 01:46:52.209420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c268412cb5'
down_revision = '817c46187e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vote_option_id_fkey', 'vote', type_='foreignkey')
    op.drop_column('vote', 'option_id')
    op.drop_table('option')
    op.add_column('vote', sa.Column('voted_for', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vote_option_id_fkey', 'vote', 'option', ['option_id'], ['id'])
    op.drop_column('vote', 'voted_for')
    op.create_table('option',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name='option_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='option_pkey')
    )
    # ### end Alembic commands ###
