"""empty message

Revision ID: ab94b516a6a5
Revises: 781a0cb0859d
Create Date: 2019-09-15 08:37:52.536829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab94b516a6a5'
down_revision = '781a0cb0859d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('discussion_creator_fkey', 'discussion', type_='foreignkey')
    op.create_foreign_key(None, 'discussion', 'user', ['creator_id'], ['id'])
    op.drop_column('discussion', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'discussion', type_='foreignkey')
    op.create_foreign_key('discussion_creator_fkey', 'discussion', 'user', ['creator'], ['id'])
    op.drop_column('discussion', 'creator_id')
    # ### end Alembic commands ###
