"""empty message

Revision ID: ef4b77337603
Revises: d4aa6bcb51bd
Create Date: 2019-09-14 22:48:38.076410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4b77337603'
down_revision = 'd4aa6bcb51bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('section', sa.Column('discussion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'section', 'discussion', ['discussion_id'], ['id'])
    op.add_column('vote', sa.Column('option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vote', 'option', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_column('vote', 'option_id')
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.drop_column('section', 'discussion_id')
    op.drop_table('option')
    # ### end Alembic commands ###
